runner:
  golangci:
    cmd: golangci-lint run --timeout 5m --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'

  # https://github.com/quasilyte/go-consistent
  # TODO: Temporary solution until added to golangci-lint: https://github.com/golangci/golangci-lint/issues/288
  goconsistent:
    cmd: go-consistent -v $(go list ./...)
    errorformat:
      - '%f:%l:%c: %m'
