name: Code Quality

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language:
          - go

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build Project
        run: make build
