name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language:
          - go

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build Project
        run: make build

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.14.1

      - name: Run Reviewdog
        run: make reviewdog-pr
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PR Lint
        uses: seferov/pr-lint-action@master
        with:
          title-regex: ^AR-\d+:.*$
          error-message: Add AR prefix and Issue ID to your title
